config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
# frozen_string_literal: true

class TodoItem < ApplicationRecord
  belongs_to :todo_list

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
# frozen_string_literal: true

class TodoList < ApplicationRecord
  has_many :todo_items, dependent: :delete_all
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todo_lists
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  def after_sign_in_path_for(_resource)
    '/todo_lists'
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home
    @todo_list = TodoList.all
  end
end

app/controllers/todo_items_controller.rb
# frozen_string_literal: true

class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
      flash[:success] = 'Todo List item was deleted.'
    else
      flash[:error] = 'Todo List item could not be deleted.'
    end
    redirect_to @todo_list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: 'Todo item completed'
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item_params
    params[:todo_item].permit(:content, :id)
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
end

app/controllers/todo_lists_controller.rb
# frozen_string_literal: true

class TodoListsController < ApplicationController
  before_action :set_todo_list, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.where(user: current_user)
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show; end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit; end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.user = current_user

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to @todo_list, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_todo_list
    @todo_list = TodoList.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def todo_list_params
    params.require(:todo_list).permit(:title, :description, :id)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/todo_items_helper.rb
# frozen_string_literal: true

module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
# frozen_string_literal: true

module TodoListsHelper
end

app/views/layouts/_alerts.slim
p.notice
  = notice
p.alert
  = alert

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" rel="stylesheet"
    title Todo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" type="text/css"
    link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet"
  body
    .container
      = render "layouts/alerts"
      = yield
    script crossorigin="anonymous" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
    script crossorigin="anonymous" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
    script crossorigin="anonymous" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 

app/views/pages/home.slim
.row-fluid
  .span10.offset1
    .hero-unit
      h1 align="center" ToDo app
br
br
- if current_user
  = link_to "Log Out", destroy_user_session_path, method: :delete
- else
  = link_to "Sign Up", new_user_registration_path
  |        
  = link_to "Log In", new_user_session_path

app/views/todo_items/_form.slim
= simple_form_for([@todo_list, @todo_list.todo_items.build]) do |f|
  = f.input :content, as: :text, label: false, placeholder: "New Todo", required: true
  = f.submit

app/views/todo_items/_todo_item.slim
.row.clearfix
  - if todo_item.completed?
    .complete
      = link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do
        i.fa.fa-check style=("opacity: 0.4;") 
    .todo_item
      p style=("opacity: 0.4;") 
        s= todo_item.content
    .trash
      = link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do
        i.fa.fa-trash
  - else
    .complete
      = link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do
        i.fa.fa-circle-thin
    .todo_item
      p= todo_item.content
    .trash
      = link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do
        i.fa.fa-trash

app/views/todo_lists/_form.slim
= form_with(model: todo_list, local: true) do |form|
  - if todo_list.errors.any?
    #error-explanation
      h2
        = pluralize(todo_list.errors.count, "error")
        | prohibited this todo_list from being saved:
      ul
        - todo_list.errors.full.messages.each do |message|
          li= message
  .field
    = form.label :title
    = form.text_field :title, required: true
  .field
    = form.label :description
    = form.text_area :description
  .actions
    = form.button :Create, class: "btn btn-dark"

app/views/todo_lists/edit.slim
h1.todo_list_title Editing Todo List
.forms
  = render 'form', todo_list: @todo_list
.links
  = link_to 'Cancel', todo_lists_path

app/views/todo_lists/index.slim
div style="text-align:right" 
  = link_to('Logout', destroy_user_session_path, method: :delete)
  div style=("text-align:left; inline-block; float:left;") 
    = link_to('User Options', edit_user_registration_path)
br
- @todo_lists.each do |todo_list|
  - if todo_list.user == current_user
    .index_row.clearfix
      h2.todo_list_title= link_to todo_list.title, todo_list
      p.todo_list_sub_title= todo_list.description
.links style="text-align:center" 
  = link_to "New Todo List", new_todo_list_path, class:"btn btn-primary"

app/views/todo_lists/new.slim
h1.todo_list_title New Todo List
.forms
  = render 'form', todo_list: @todo_list
.links
  = link_to 'Back', todo_lists_path

app/views/todo_lists/show.slim
p#notice= notice
h2.todo_list_title= @todo_list.title
p.todo_list_sub_title= @todo_list.description
#todo_items_wrapper
  = render @todo_list.todo_items
  #form
    = render "todo_items/form"
.links
  = link_to 'Edit', edit_todo_list_path(@todo_list)
  |        
  = link_to 'Back', todo_lists_path
  |        
  = link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }